version: '3.4'
networks:
  cinco:
volumes:
  keycloak-data:
    external: true
services:
  rooms:
    container_name: rooms
    build: .
    ports:
      - 3000:3000
    networks:
      - cinco
      #depends_on:
      #- oauth

  keycloak:
    container_name: keycloak
    image: jboss/keycloak:latest
    ports:
      - "8090:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=a12345678
      - KEYCLOAK_FRONTEND_URL=http://localhost:8090
    volumes:
      - keycloak-data:/opt/jboss/keycloak/standalone/data
    networks:
      - cinco

  database:
    container_name: mongo
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    networks:
      - cinco
