version: '3.4'
networks:
  cinco:
services:
  rooms:
    container_name: rooms
    build: .
    ports:
      - 8085:8085
    networks:
      - cinco
    depends_on:
      - database

  database:
    container_name: mongo
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    networks:
      - cinco
